version: '3'

services:
  server:
    image: server
    build: 
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    command:
      - npm 
      - start
      - start
    volumes:
      - .:/server
      - node_modules:/server/node_modules
    ports:
      - "3000:3001"
    # links:
    #   - mongodb
    # depends_on:
    #   - mongodb
      
  # mongodb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
    
volumes:
  node_modules: {}